[package]
name = "vim-linked"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "linked"
crate-type = ["cdylib"]      # Creates dynamic lib

[dependencies]
miniserde = "0.1"
pulldown-cmark = "0.9"
